### ISSUE TITLE
reportをGitHub Pagesにデプロイ＆自動化

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#188]
## 概要

- JacocoReport等をGitHub Pagesに上げたい
- それの自動化したい

**Comment by sunakan** [comment]
[新しいGitHub Pagesのデプロイ方法を試す](https://zenn.dev/ssssota/articles/f2509a21b768ed)

記事公開日は2022年7月29日

このときはbetaだったらしい

その前は

> いままで GitHub Pages へデプロイする際は、ブランチを指定する方法や、デフォルトブランチの特定のディレクトリを指定していました。

> また、これを GitHub Actions で行うために、日本人作者の [peaceiris/actions-gh-pages](https://github.com/marketplace/actions/github-pages-action) を利用したことがある人も多いと思います。

現在（2022年9月20日時点）のバージョンはv1.2

https://github.com/marketplace/actions/deploy-github-pages-site

----

## GitHubの [actions/deploy-pages](https://github.com/actions/deploy-pages)

> ⚠️ Official support for building Pages with Actions is in public beta at the moment.

ただ今もBeta版っぽい

**Comment by sunakan** [comment]
## deploy-pages

> This action is used to deploy Actions artifacts to GitHub Pages.

Actionsのアーティファクト（成果物）をGitHub Pagesにデプロイ

これ入れる前に、先にアーティファクト（成果物）をアップロードする機構が先

**Comment by sunakan** [comment]
https://github.com/actions/upload-pages-artifact

これ使いそう

**Comment by sunakan** [comment]
GitHub ActionsのArtifactの削除やら上限

[GitHub ActionsのArtifactを削除したい](https://blog.e2info.co.jp/2020/11/12/github_actions_artifact/)

> GitHub ActionsのArtifactの上限よくわからなかったんだけど、無料で利用している場合、、おそらく2GBっぽい。 上限に達すると以下のエラーとなり、アップロードができなくなります。

> Artifactは90日で自動削除されるのですが、ビルド頻度によっては削除されるのを待っていられないため、古いArtifactを自動的に削除する設定をいれてみました。


上限：2GB
自動削除：90日

**Comment by sunakan** [comment]
公式

https://docs.github.com/ja/actions/managing-workflow-runs/removing-workflow-artifacts

> By default, GitHub stores build logs and artifacts for 90 days, and this retention period can be customized. For more information, see "[Usage limits, billing, and administration](https://docs.github.com/ja/actions/reference/usage-limits-billing-and-administration#artifact-and-log-retention-policy)."

90日

**Comment by sunakan** [comment]
```yml
      - name: テストカバレッジレポートを成果物(アーティファクト)にする
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/reports/jacoco/test/html/
```

上をやるだけで、以下のようなArtifactができる

<img width="600" alt="image" src="https://user-images.githubusercontent.com/43210698/194699084-f5fdd718-4725-4dc9-ac5a-92b7454376d3.png">

**Comment by sunakan** [comment]
actions/deploy-pages@v1は `id-token: write` をご所望

<img width="400" alt="image" src="https://user-images.githubusercontent.com/43210698/194700541-9edc4c6e-8d8c-4bd0-87ed-4c4a41f980f9.png">

**Comment by sunakan** [comment]
以下みたいなエラーが出たとき

```
Branch "ブランチ名" is not allowed to deploy to github-pages due to environment protection rules.
```

以下で、許可するブランチを設定する（デフォはmainのみ）

<img width="600" alt="スクリーンショット 2022-10-08 18 52 44" src="https://user-images.githubusercontent.com/43210698/194701621-62c29a55-c12c-4e5a-8490-ff2ecc7f45cd.png">

**Comment by sunakan** [comment]
https://sunakan.github.io/realworld-kotlin-springboot-jdbc/

**Comment by sunakan** [comment]
成果物を作るAction

```yml
      - name: テストカバレッジレポートを成果物(アーティファクト)にする
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/reports/jacoco/test/html/
```

成果物をGitHub PagesにデプロイするAction

```yml
  #
  # GitHub Pagesにデプロイ
  #
  # - 権限を最小にするため、別jobで表現
  # - ホスティング先: https://${名前}.github.io/${リポジトリ名}/
  #
  deploy-pages:
    if: github.ref == 'refs/heads/main'
    needs: ci-test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: 成果物(アーティファクト)をGitHub Pagesにデプロイ
        uses: actions/deploy-pages@v1
```
