### ISSUE TITLE
調査：CIで"Option FILES is deprecated, please use JUNIT_FILES instead!" Warningがあった

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#199]
## 概要

- GithubActions の ci-testで `Option FILES is deprecated, please use JUNIT_FILES instead!` という警告が出ていた

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43210698/191450219-34419e7f-ff7a-45f9-93de-391d8e6877c9.png">

**Comment by sunakan** [comment]
GitHubActionsで使っているci.yml中の

```yml
      - name: テスト結果レポートをGitHub Actionsの上部に公開
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: 'JUnit5のテスト結果レポート'
          files: 'build/test-results/**/*.xml'
```

のfilesではなくjunit_filesを使えって言ってそう

https://github.com/EnricoMi/publish-unit-test-result-action

や

https://github.com/marketplace/actions/publish-test-results

でもjunit_filesを使う例になっている。。最初からそうだった？
