### ISSUE TITLE
調査：CodeClimateのCodeのSourceが出ない件

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#236]
Codeタブ > 適当なktファイル > Source > なにもでない

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43210698/194046333-722798f5-baaf-4836-8b3e-4c2e82195470.png">

こういうのが出て欲しい

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43210698/194046674-adf0c330-4d3c-44f0-b51d-7d982c153a5c.png">

**Comment by sunakan** [comment]
## 怪しいと思っているのは。。

`./gradlew test` がJUnitTestせず、レポートのディレクトリがなんかおかしいとか？

勘

**Comment by sunakan** [comment]
CodeClimateにレポートを送ってる Action を見てみる

https://github.com/paambaati/codeclimate-action

**Comment by sunakan** [comment]
```yml
- name: '【mainブランチ】 make test.full && テストカバレッジレポートをCodeClimateに送る'
  if: github.ref == 'refs/heads/main'
  uses: paambaati/codeclimate-action@v3.0.0
  with:
    coverageCommand: make test.full
    coverageLocations: 'build/reports/jacoco/test/jacocoTestReport.xml:jacoco'
  env:
    CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    JACOCO_SOURCE_PATH: ${{ github.workspace }}/src/main/kotlin
    TZ: Asia/Tokyo
```
