### ISSUE TITLE
CodeCov導入

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#256]
## 目的

CodeClimateがおかしい時用のサブ

## 手順

1. GitHubでログイン
2. Reposタブ > 右側のNot yet setupボタン > 検索 > setup repo
<img width="400" alt="image" src="https://user-images.githubusercontent.com/43210698/195977929-fa02e057-625c-43a0-915d-61367eceaaa5.png">

3. Let's get you repo covered

### 【CodeCov】Step 1. CODECOV_TOKENがあるのでコピーしてCIの環境変数へ

<img width="300" alt="スクリーンショット 2022-10-23 12 44 49" src="https://user-images.githubusercontent.com/43210698/197372652-08815391-08b2-45b7-a98e-c83b9bee8cec.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43210698/197372860-940f41f7-6fc4-42fb-af8f-02f1baaac53d.png">

### Step 2. ci.ymlに組み込む

これをすることで、カバレッジレポートをCodecovに送ることができる

.github/workflows/ci.yml

```yml
      - name: '【mainブランチ】 テストカバレッジレポートをCodecovに送る'
        #if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```

ブランチ毎にレポートは管理されてそう（でも基本mainブランチだけにするかも）

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43210698/197374344-328235c0-3a11-440b-8a33-3395ecebbb79.png">

### 番外

バッジのリンクの場所（使いみち：READMEに貼る）

[![codecov](https://codecov.io/gh/sunakan/realworld-kotlin-springboot-jdbc/branch/main/graph/badge.svg?token=5G1AY9M4JE)](https://codecov.io/gh/sunakan/realworld-kotlin-springboot-jdbc)

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43210698/197374284-83f6ed33-aa3c-4b28-8952-825653d0f972.png">
