### ISSUE TITLE
HttpStatusをハードコーディング→HttpStatusのenumを利用する

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#271]
## 背景

lintツール：detektのデフォに合わせていきたい（現状は200などの固定値を許している）

```yml
  #
  # MagicNumber
  #
  # 概要
  # - マジックナンバーはOUT
  #
  MagicNumber:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**', '**/*.kts']
    ignoreNumbers: # (default: ['-1', '0', '1', 2])
      - '-1'
      - '0'
      - '1'
      - '2'
      - '200'
      - '201'
      - '400'
      - '401'
      - '403'
      - '404'
      - '422'
      - '500'
```

## 実際の対応例

Before

```kt
val expectedStatus = 200
```

After

```kt
val expectedStatus = HttpStatus.OK.value()
```
